# Generated by Django 4.1.2 on 2022-12-09 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuredMembers',
            fields=[
                ('cust_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('agnt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Insurances',
            fields=[
                ('insurance_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('insurance_type', models.CharField(choices=[('health', 'health insurance'), ('property', 'property insurance'), ('life', 'life insurance')], max_length=100)),
                ('cust_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuredmembers')),
            ],
        ),
        migrations.CreateModel(
            name='CustAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuredmembers')),
            ],
        ),
    ]
