# Generated by Django 4.1.2 on 2022-12-09 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custaddress',
            name='cust',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuredmembers'),
        ),
        migrations.AlterField(
            model_name='insurances',
            name='cust_key',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='insurance_app.insuredmembers'),
        ),
    ]
